version: "3.4"


services:
  redis:
    image: redis:5-alpine
    hostname: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASS:-}"]
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  app:
    image: traktogram
    build:
      context: .
      args:
        - installargs=--no-dev
    env_file:
      - .envs/prod.env
    stop_signal: SIGINT
    depends_on:
      - redis
    command: ["python", "traktogram/entry.py"]


volumes:
  redis-data:
