[tool.poetry]
name = "teletrakt"
version = "0.1.0"
description = ""
authors = ["Bachynin Ivan <bachynin.i@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
python-telegram-bot = "^12.3.0"
redis = "^3.3.11"
python-dotenv = "^0.10.5"
colorlog = "^4.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
